[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "PauloK3tchup", email = "passandoalimpo13@gmail.com"},
]
dependencies = []
requires-python = ">=3.10"
license = {text = "MIT"}
